<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>BakeryApp.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BakeryApp.BLL/BakeryApp.BLL.csproj" />
    <ProjectReference Include="../BakeryApp.DAL/BakeryApp.DAL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>
