<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>BakeryApp.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BakeryApp.BLL/BakeryApp.BLL.csproj" />
    <ProjectReference Include="../BakeryApp.DAL/BakeryApp.DAL.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
  </ItemGroup>
</Project>
